version: '3'
volumes:
  node_modules:
services:
  # web:
  #   image: nginx:alpine
  #   volumes:
  #     - .:/usr/src/app:cached
  #     - ./nginx:/etc/nginx/conf.d/default.conf
  #   ports:
  #     - "8080:80"
  app:
    build: .
    container_name: fronted
    command: yarn run dev
    volumes:
        - .:/usr/src/app:cached
        - node_modules:/usr/src/app/node_modules
    ports:
      - "8082:8082"

networks:
  default:
    external:
      name: thrive_jky
